/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BibleVerse {
  'verse' : bigint,
  'book' : string,
  'text' : string,
  'chapter' : bigint,
}
export interface Bookmarks { 'verse' : BibleVerse, 'note' : string }
export interface DevotionalDay {
  'title' : string,
  'action' : string,
  'scripture' : string,
  'dayNumber' : bigint,
  'guidance' : string,
  'reflection' : string,
}
export interface FastHistory {
  'startTime' : Time,
  'endTime' : Time,
  'goalHours' : bigint,
  'timestamp' : bigint,
  'reflectionJournal' : string,
}
export interface FastingContent {
  'completionEncouragement' : string,
  'description' : string,
  'reflectionPrompt' : string,
  'scriptureReferences' : Array<VerseReference>,
  'hourlyEncouragement' : Array<string>,
}
export interface FastingSession {
  'startTime' : [] | [Time],
  'status' : { 'notStarted' : null } |
    { 'completed' : null } |
    { 'inProgress' : { 'elapsed' : bigint } },
  'goalHours' : bigint,
  'timestamp' : Time,
  'reflectionJournal' : string,
}
export interface JournalEntry {
  'content' : string,
  'linkedScriptures' : Array<VerseReference>,
  'dayNumber' : bigint,
}
export interface MinistryInfo {
  'missionStatement' : string,
  'email' : string,
  'website' : string,
  'address' : string,
  'supportLink' : string,
}
export interface Reminder {
  'time' : bigint,
  'enabled' : boolean,
  'message' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerseReference {
  'book' : string,
  'verseStart' : bigint,
  'chapter' : bigint,
  'verseEnd' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJournalEntry' : ActorMethod<[bigint, string], undefined>,
  'addLinkedScripture' : ActorMethod<[bigint, VerseReference], undefined>,
  'addReminder' : ActorMethod<[bigint, boolean, string], undefined>,
  'addVerseBookmark' : ActorMethod<[BibleVerse, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelCurrentFast' : ActorMethod<[], boolean>,
  'completeFast' : ActorMethod<[string], boolean>,
  'getAllBibleVerses' : ActorMethod<[], Array<BibleVerse>>,
  'getAllFastingSessions' : ActorMethod<[], Array<FastingSession>>,
  'getAllJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getBibleVerse' : ActorMethod<[string, bigint, bigint], [] | [BibleVerse]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentDay' : ActorMethod<[], bigint>,
  'getDevotionalDay' : ActorMethod<[bigint], DevotionalDay>,
  'getFastingContent' : ActorMethod<[], FastingContent>,
  'getFastingHistory' : ActorMethod<[], Array<FastHistory>>,
  'getFastingProgress' : ActorMethod<[], FastingSession>,
  'getMinistryInfo' : ActorMethod<[], MinistryInfo>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'getUserDay' : ActorMethod<[Principal], bigint>,
  'getVerseBookmarks' : ActorMethod<[], Array<Bookmarks>>,
  'initializeBibleVerses' : ActorMethod<
    [Array<[string, bigint, bigint, string]>],
    undefined
  >,
  'initializeDevotionalDays' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<Principal>>,
  'removeLinkedScripture' : ActorMethod<[bigint, VerseReference], undefined>,
  'removeVerseBookmark' : ActorMethod<[BibleVerse], undefined>,
  'searchBible' : ActorMethod<[string], Array<BibleVerse>>,
  'setCurrentDay' : ActorMethod<[bigint], undefined>,
  'startNewFast' : ActorMethod<[bigint], boolean>,
  'updateFastingProgress' : ActorMethod<[], boolean>,
  'updateReminderStatus' : ActorMethod<[bigint, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];