/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VerseReference = IDL.Record({
  'book' : IDL.Text,
  'verseStart' : IDL.Nat,
  'chapter' : IDL.Nat,
  'verseEnd' : IDL.Nat,
});
export const BibleVerse = IDL.Record({
  'verse' : IDL.Nat,
  'book' : IDL.Text,
  'text' : IDL.Text,
  'chapter' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const FastingSession = IDL.Record({
  'startTime' : IDL.Opt(Time),
  'status' : IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Record({ 'elapsed' : IDL.Int }),
  }),
  'goalHours' : IDL.Nat,
  'timestamp' : Time,
  'reflectionJournal' : IDL.Text,
});
export const JournalEntry = IDL.Record({
  'content' : IDL.Text,
  'linkedScriptures' : IDL.Vec(VerseReference),
  'dayNumber' : IDL.Nat,
});
export const DevotionalDay = IDL.Record({
  'title' : IDL.Text,
  'action' : IDL.Text,
  'scripture' : IDL.Text,
  'dayNumber' : IDL.Nat,
  'guidance' : IDL.Text,
  'reflection' : IDL.Text,
});
export const FastingContent = IDL.Record({
  'completionEncouragement' : IDL.Text,
  'description' : IDL.Text,
  'reflectionPrompt' : IDL.Text,
  'scriptureReferences' : IDL.Vec(VerseReference),
  'hourlyEncouragement' : IDL.Vec(IDL.Text),
});
export const FastHistory = IDL.Record({
  'startTime' : Time,
  'endTime' : Time,
  'goalHours' : IDL.Nat,
  'timestamp' : IDL.Int,
  'reflectionJournal' : IDL.Text,
});
export const MinistryInfo = IDL.Record({
  'missionStatement' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'supportLink' : IDL.Text,
});
export const Reminder = IDL.Record({
  'time' : IDL.Nat,
  'enabled' : IDL.Bool,
  'message' : IDL.Text,
});
export const Bookmarks = IDL.Record({
  'verse' : BibleVerse,
  'note' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJournalEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addLinkedScripture' : IDL.Func([IDL.Nat, VerseReference], [], []),
  'addReminder' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Text], [], []),
  'addVerseBookmark' : IDL.Func([BibleVerse, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelCurrentFast' : IDL.Func([], [IDL.Bool], []),
  'completeFast' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllBibleVerses' : IDL.Func([], [IDL.Vec(BibleVerse)], ['query']),
  'getAllFastingSessions' : IDL.Func([], [IDL.Vec(FastingSession)], ['query']),
  'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getBibleVerse' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Opt(BibleVerse)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentDay' : IDL.Func([], [IDL.Nat], ['query']),
  'getDevotionalDay' : IDL.Func([IDL.Nat], [DevotionalDay], ['query']),
  'getFastingContent' : IDL.Func([], [FastingContent], ['query']),
  'getFastingHistory' : IDL.Func([], [IDL.Vec(FastHistory)], ['query']),
  'getFastingProgress' : IDL.Func([], [FastingSession], ['query']),
  'getMinistryInfo' : IDL.Func([], [MinistryInfo], ['query']),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getUserDay' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getVerseBookmarks' : IDL.Func([], [IDL.Vec(Bookmarks)], ['query']),
  'initializeBibleVerses' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat, IDL.Text))],
      [],
      [],
    ),
  'initializeDevotionalDays' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'removeLinkedScripture' : IDL.Func([IDL.Nat, VerseReference], [], []),
  'removeVerseBookmark' : IDL.Func([BibleVerse], [], []),
  'searchBible' : IDL.Func([IDL.Text], [IDL.Vec(BibleVerse)], ['query']),
  'setCurrentDay' : IDL.Func([IDL.Nat], [], []),
  'startNewFast' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateFastingProgress' : IDL.Func([], [IDL.Bool], []),
  'updateReminderStatus' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VerseReference = IDL.Record({
    'book' : IDL.Text,
    'verseStart' : IDL.Nat,
    'chapter' : IDL.Nat,
    'verseEnd' : IDL.Nat,
  });
  const BibleVerse = IDL.Record({
    'verse' : IDL.Nat,
    'book' : IDL.Text,
    'text' : IDL.Text,
    'chapter' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const FastingSession = IDL.Record({
    'startTime' : IDL.Opt(Time),
    'status' : IDL.Variant({
      'notStarted' : IDL.Null,
      'completed' : IDL.Null,
      'inProgress' : IDL.Record({ 'elapsed' : IDL.Int }),
    }),
    'goalHours' : IDL.Nat,
    'timestamp' : Time,
    'reflectionJournal' : IDL.Text,
  });
  const JournalEntry = IDL.Record({
    'content' : IDL.Text,
    'linkedScriptures' : IDL.Vec(VerseReference),
    'dayNumber' : IDL.Nat,
  });
  const DevotionalDay = IDL.Record({
    'title' : IDL.Text,
    'action' : IDL.Text,
    'scripture' : IDL.Text,
    'dayNumber' : IDL.Nat,
    'guidance' : IDL.Text,
    'reflection' : IDL.Text,
  });
  const FastingContent = IDL.Record({
    'completionEncouragement' : IDL.Text,
    'description' : IDL.Text,
    'reflectionPrompt' : IDL.Text,
    'scriptureReferences' : IDL.Vec(VerseReference),
    'hourlyEncouragement' : IDL.Vec(IDL.Text),
  });
  const FastHistory = IDL.Record({
    'startTime' : Time,
    'endTime' : Time,
    'goalHours' : IDL.Nat,
    'timestamp' : IDL.Int,
    'reflectionJournal' : IDL.Text,
  });
  const MinistryInfo = IDL.Record({
    'missionStatement' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'supportLink' : IDL.Text,
  });
  const Reminder = IDL.Record({
    'time' : IDL.Nat,
    'enabled' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Bookmarks = IDL.Record({ 'verse' : BibleVerse, 'note' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJournalEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addLinkedScripture' : IDL.Func([IDL.Nat, VerseReference], [], []),
    'addReminder' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Text], [], []),
    'addVerseBookmark' : IDL.Func([BibleVerse, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelCurrentFast' : IDL.Func([], [IDL.Bool], []),
    'completeFast' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllBibleVerses' : IDL.Func([], [IDL.Vec(BibleVerse)], ['query']),
    'getAllFastingSessions' : IDL.Func(
        [],
        [IDL.Vec(FastingSession)],
        ['query'],
      ),
    'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getBibleVerse' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Opt(BibleVerse)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentDay' : IDL.Func([], [IDL.Nat], ['query']),
    'getDevotionalDay' : IDL.Func([IDL.Nat], [DevotionalDay], ['query']),
    'getFastingContent' : IDL.Func([], [FastingContent], ['query']),
    'getFastingHistory' : IDL.Func([], [IDL.Vec(FastHistory)], ['query']),
    'getFastingProgress' : IDL.Func([], [FastingSession], ['query']),
    'getMinistryInfo' : IDL.Func([], [MinistryInfo], ['query']),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getUserDay' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getVerseBookmarks' : IDL.Func([], [IDL.Vec(Bookmarks)], ['query']),
    'initializeBibleVerses' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat, IDL.Text))],
        [],
        [],
      ),
    'initializeDevotionalDays' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'removeLinkedScripture' : IDL.Func([IDL.Nat, VerseReference], [], []),
    'removeVerseBookmark' : IDL.Func([BibleVerse], [], []),
    'searchBible' : IDL.Func([IDL.Text], [IDL.Vec(BibleVerse)], ['query']),
    'setCurrentDay' : IDL.Func([IDL.Nat], [], []),
    'startNewFast' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateFastingProgress' : IDL.Func([], [IDL.Bool], []),
    'updateReminderStatus' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };