/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FastingSession {
    startTime?: Time;
    status: {
        __kind__: "notStarted";
        notStarted: null;
    } | {
        __kind__: "completed";
        completed: null;
    } | {
        __kind__: "inProgress";
        inProgress: {
            elapsed: bigint;
        };
    };
    goalHours: bigint;
    timestamp: Time;
    reflectionJournal: string;
}
export type Time = bigint;
export interface Reminder {
    time: bigint;
    enabled: boolean;
    message: string;
}
export interface JournalEntry {
    content: string;
    linkedScriptures: Array<VerseReference>;
    dayNumber: bigint;
}
export interface FastingContent {
    completionEncouragement: string;
    description: string;
    reflectionPrompt: string;
    scriptureReferences: Array<VerseReference>;
    hourlyEncouragement: Array<string>;
}
export interface MinistryInfo {
    missionStatement: string;
    email: string;
    website: string;
    address: string;
    supportLink: string;
}
export interface FastHistory {
    startTime: Time;
    endTime: Time;
    goalHours: bigint;
    timestamp: bigint;
    reflectionJournal: string;
}
export interface DevotionalDay {
    title: string;
    action: string;
    scripture: string;
    dayNumber: bigint;
    guidance: string;
    reflection: string;
}
export interface Bookmarks {
    verse: BibleVerse;
    note: string;
}
export interface VerseReference {
    book: string;
    verseStart: bigint;
    chapter: bigint;
    verseEnd: bigint;
}
export interface BibleVerse {
    verse: bigint;
    book: string;
    text: string;
    chapter: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addJournalEntry(day: bigint, content: string): Promise<void>;
    addLinkedScripture(day: bigint, reference: VerseReference): Promise<void>;
    addReminder(time: bigint, enabled: boolean, message: string): Promise<void>;
    addVerseBookmark(verse: BibleVerse, note: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelCurrentFast(): Promise<boolean>;
    completeFast(reflectionJournal: string): Promise<boolean>;
    getAllBibleVerses(): Promise<Array<BibleVerse>>;
    getAllFastingSessions(): Promise<Array<FastingSession>>;
    getAllJournalEntries(): Promise<Array<JournalEntry>>;
    getBibleVerse(book: string, chapter: bigint, verse: bigint): Promise<BibleVerse | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentDay(): Promise<bigint>;
    getDevotionalDay(day: bigint): Promise<DevotionalDay>;
    getFastingContent(): Promise<FastingContent>;
    getFastingHistory(): Promise<Array<FastHistory>>;
    getFastingProgress(): Promise<FastingSession>;
    getMinistryInfo(): Promise<MinistryInfo>;
    getReminders(): Promise<Array<Reminder>>;
    getUserDay(user: Principal): Promise<bigint>;
    getVerseBookmarks(): Promise<Array<Bookmarks>>;
    initializeBibleVerses(verses: Array<[string, bigint, bigint, string]>): Promise<void>;
    initializeDevotionalDays(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listAllUsers(): Promise<Array<Principal>>;
    removeLinkedScripture(day: bigint, reference: VerseReference): Promise<void>;
    removeVerseBookmark(verse: BibleVerse): Promise<void>;
    searchBible(term: string): Promise<Array<BibleVerse>>;
    setCurrentDay(day: bigint): Promise<void>;
    startNewFast(goalHours: bigint): Promise<boolean>;
    updateFastingProgress(): Promise<boolean>;
    updateReminderStatus(index: bigint, enabled: boolean): Promise<boolean>;
}
import type { BibleVerse as _BibleVerse, FastingSession as _FastingSession, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addJournalEntry(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(arg0, arg1);
            return result;
        }
    }
    async addLinkedScripture(arg0: bigint, arg1: VerseReference): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLinkedScripture(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLinkedScripture(arg0, arg1);
            return result;
        }
    }
    async addReminder(arg0: bigint, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReminder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReminder(arg0, arg1, arg2);
            return result;
        }
    }
    async addVerseBookmark(arg0: BibleVerse, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVerseBookmark(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVerseBookmark(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelCurrentFast(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelCurrentFast();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelCurrentFast();
            return result;
        }
    }
    async completeFast(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeFast(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeFast(arg0);
            return result;
        }
    }
    async getAllBibleVerses(): Promise<Array<BibleVerse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBibleVerses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBibleVerses();
            return result;
        }
    }
    async getAllFastingSessions(): Promise<Array<FastingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFastingSessions();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFastingSessions();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJournalEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJournalEntries();
            return result;
        }
    }
    async getBibleVerse(arg0: string, arg1: bigint, arg2: bigint): Promise<BibleVerse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBibleVerse(arg0, arg1, arg2);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBibleVerse(arg0, arg1, arg2);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentDay(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentDay();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentDay();
            return result;
        }
    }
    async getDevotionalDay(arg0: bigint): Promise<DevotionalDay> {
        if (this.processError) {
            try {
                const result = await this.actor.getDevotionalDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDevotionalDay(arg0);
            return result;
        }
    }
    async getFastingContent(): Promise<FastingContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getFastingContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFastingContent();
            return result;
        }
    }
    async getFastingHistory(): Promise<Array<FastHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFastingHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFastingHistory();
            return result;
        }
    }
    async getFastingProgress(): Promise<FastingSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getFastingProgress();
                return from_candid_FastingSession_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFastingProgress();
            return from_candid_FastingSession_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMinistryInfo(): Promise<MinistryInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getMinistryInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMinistryInfo();
            return result;
        }
    }
    async getReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminders();
            return result;
        }
    }
    async getUserDay(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDay(arg0);
            return result;
        }
    }
    async getVerseBookmarks(): Promise<Array<Bookmarks>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerseBookmarks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerseBookmarks();
            return result;
        }
    }
    async initializeBibleVerses(arg0: Array<[string, bigint, bigint, string]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeBibleVerses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeBibleVerses(arg0);
            return result;
        }
    }
    async initializeDevotionalDays(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDevotionalDays();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDevotionalDays();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return result;
        }
    }
    async removeLinkedScripture(arg0: bigint, arg1: VerseReference): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeLinkedScripture(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeLinkedScripture(arg0, arg1);
            return result;
        }
    }
    async removeVerseBookmark(arg0: BibleVerse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeVerseBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeVerseBookmark(arg0);
            return result;
        }
    }
    async searchBible(arg0: string): Promise<Array<BibleVerse>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBible(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBible(arg0);
            return result;
        }
    }
    async setCurrentDay(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCurrentDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCurrentDay(arg0);
            return result;
        }
    }
    async startNewFast(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.startNewFast(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startNewFast(arg0);
            return result;
        }
    }
    async updateFastingProgress(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFastingProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFastingProgress();
            return result;
        }
    }
    async updateReminderStatus(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReminderStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReminderStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_FastingSession_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FastingSession): FastingSession {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BibleVerse]): BibleVerse | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: [] | [_Time];
    status: {
        notStarted: null;
    } | {
        completed: null;
    } | {
        inProgress: {
            elapsed: bigint;
        };
    };
    goalHours: bigint;
    timestamp: _Time;
    reflectionJournal: string;
}): {
    startTime?: Time;
    status: {
        __kind__: "notStarted";
        notStarted: null;
    } | {
        __kind__: "completed";
        completed: null;
    } | {
        __kind__: "inProgress";
        inProgress: {
            elapsed: bigint;
        };
    };
    goalHours: bigint;
    timestamp: Time;
    reflectionJournal: string;
} {
    return {
        startTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.startTime)),
        status: from_candid_variant_n7(_uploadFile, _downloadFile, value.status),
        goalHours: value.goalHours,
        timestamp: value.timestamp,
        reflectionJournal: value.reflectionJournal
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: {
        elapsed: bigint;
    };
}): {
    __kind__: "notStarted";
    notStarted: null;
} | {
    __kind__: "completed";
    completed: null;
} | {
    __kind__: "inProgress";
    inProgress: {
        elapsed: bigint;
    };
} {
    return "notStarted" in value ? {
        __kind__: "notStarted",
        notStarted: value.notStarted
    } : "completed" in value ? {
        __kind__: "completed",
        completed: value.completed
    } : "inProgress" in value ? {
        __kind__: "inProgress",
        inProgress: value.inProgress
    } : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FastingSession>): Array<FastingSession> {
    return value.map((x)=>from_candid_FastingSession_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
